name: Build and publish Docker distributions to Github Container Registry ghcr.io

on:
  push:
    branches:
      - master
      - version-*
    paths:
      - gradle.properties
      - grpc/gradle.properties

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            grpc:
              - 'grpc/gradle.properties'
        # Prepare gRPC
      - name: Get gRPC release_version
        if: ${{ steps.filter.outputs.grpc }}
        id: grpc_ver
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: grpc/gradle.properties
          properties: release_version
      - name: Set version for current build in package_info.json
        if: ${{ steps.filter.outputs.grpc }}
        uses: MerthinTechnologies/edit-json-action@v1
        with:
          filename: 'grpc/package_info.json'
          key: 'package_version'
          value: ${{ steps.grpc_ver.outputs.release_version }}
      - name: Set up Python 3.7
        if: ${{ steps.filter.outputs.grpc }}
        uses: actions/setup-python@v4
        with:
          python-version: 3.7
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        if: ${{ steps.filter.outputs.grpc }}
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Build release with Gradle
        if: ${{ steps.filter.outputs.grpc }}
        run: ./gradlew --info --warning-mode all clean build publish closeAndReleaseSonatypeStagingRepository
        env:
          ORG_GRADLE_PROJECT_sonatypeUsername: ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          ORG_GRADLE_PROJECT_sonatypePassword: ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.SONATYPE_GPG_ARMORED_KEY }}
          ORG_GRADLE_PROJECT_signingPassword: ${{ secrets.SONATYPE_SIGNING_PASSWORD }}
      - name: Build gRPC python package
        working-directory: ./grpc
        run: |
          pip install -r requirements.txt
          python setup.py generate -s
          python setup.py sdist
      - name: Publish gRPC distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          user: __token__
          password: ${{ secrets.PYPI_PASSWORD }}
          repository_url: https://upload.pypi.org/legacy/
          packages_dir: grpc/dist/
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: echo "REPOSITORY_NAME=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_OUTPUT
        id: meta
      - name: Read version from gradle.properties
        id: read_property
        uses: christian-draeger/read-properties@1.1.1
        with:
          path: ./gradle.properties
          properties: release_version
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ghcr.io/${{ github.repository }}:${{ steps.read_property.outputs.release_version }}
          labels: com.exactpro.th2.${{ steps.meta.outputs.REPOSITORY_NAME }}=${{ steps.read_property.outputs.release_version }}
          build-args: |
            release_version=${{ steps.read_property.outputs.release_version }}
